Better shell scripts

diff --git a/RPadduser b/RPadduser
--- a/RPadduser
+++ b/RPadduser
@@ -1,7 +1,12 @@
 #!/bin/bash
+
+die () {
+        echo "ERROR: $1. Aborting!"
+        exit 1
+}
+
 if [ $UID -ne 0 ]; then
-   echo "$0 must be run as root"
-   exit 1
+   die "$0 must be run as root"
 fi
 useradd -m -s /bin/bash runnerpyzza
 passwd runnerpyzza
diff --git a/RPpreparedir b/RPpreparedir
--- a/RPpreparedir
+++ b/RPpreparedir
@@ -1,13 +1,17 @@
 #!/bin/bash
+die () {
+        echo "ERROR: $1. Aborting!"
+        exit 1
+}
+
 if [ $UID -ne 0 ]; then
-   echo "$0 must be run as root"
-   exit 1
+   die "$0 must be run as root"
 fi
 mkdir /opt/runnerpyzza
 chmod 777 -R /opt/runnerpyzza
 ls /opt/runnerpyzza > /dev/null
 if [ $? -ne 0 ] ; then
-  echo "Could not create RunnerPyzza directory"
+  die "Could not create RunnerPyzza directory"
 else
   echo "RunnerPyzza directory successefully created"
 fi
diff --git a/RPsshkeys b/RPsshkeys
--- a/RPsshkeys
+++ b/RPsshkeys
@@ -1,4 +1,10 @@
 #!/bin/bash
+
+die () {
+        echo "ERROR: $1. Aborting!"
+        exit 1
+}
+
 if [ "$#" -lt 2 ]; then
     echo './RPsshkeys USERNAME HOSTNAME'
     exit 65
@@ -10,5 +16,5 @@ if [ -f ~/.ssh/id_rsa ]; then
 else
     ssh-keygen -t rsa
 fi
-ssh-add
-ssh-copy-id $USER@$HOST
+ssh-add || die "could not add the keys"
+ssh-copy-id $USER@$HOST || "could not copy the keys to $HOST"
